# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = '8dafe6c9cbf2f0b733e82c09e4ef7f8c4721a883 *'
__dependency_versions__ = {
}
__all__ = (
    '__version__',
    '__repo_version__',
    '__fingerprint__',
    '__dependency_versions__',
)
